import os

TRANSFORMED_TEXT_COLUMN = os.getenv("TRANSFORMED_TEXT_COLUMN", "Free_Text")
CSV_READING_FILE = os.getenv("CSV_READING_FILE", "output-mutmam.csv")
CSV_OUTPUT_FILE = os.getenv("CSV_OUTPUT_FILE", "TransformedData.csv")
PERCENTAGE_COLUMN = os.getenv("PERCENTAGE_COLUMN", "Redundancy")
ORIGINAL_TEXT_COLUMN = os.getenv("ORIGINAL_TEXT_COLUMN", "Output_Text")
FUZZY_MATCH_PERCENTAGE = os.getenv("FUZZY_MATCH_PERCENTAGE", 95)
ENCODING_FORMAT = os.getenv("ENCODING_FORMAT", 'utf-8-sig')
FUZZY_SUBTYPE_MATCH_PERCENTAGE = os.getenv("FUZZY_SUBTYPE_MATCH_PERCENTAGE", 98)
